//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.21 at 05:06:59 PM MSK 
//


package medicine;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the medicine package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Medicine_QNAME = new QName("medicine", "medicine");
    private final static QName _Certificated_QNAME = new QName("medicine", "certificated");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: medicine
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Medicines }
     * 
     */
    public Medicines createMedicines() {
        return new Medicines();
    }

    /**
     * Create an instance of {@link Medicine }
     * 
     */
    public Medicine createMedicine() {
        return new Medicine();
    }

    /**
     * Create an instance of {@link Certificated }
     * 
     */
    public Certificated createCertificated() {
        return new Certificated();
    }

    /**
     * Create an instance of {@link Dosage }
     * 
     */
    public Dosage createDosage() {
        return new Dosage();
    }

    /**
     * Create an instance of {@link Certificate }
     * 
     */
    public Certificate createCertificate() {
        return new Certificate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Medicine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "medicine", name = "medicine")
    public JAXBElement<Medicine> createMedicine(Medicine value) {
        return new JAXBElement<Medicine>(_Medicine_QNAME, Medicine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Certificated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "medicine", name = "certificated", substitutionHeadNamespace = "medicine", substitutionHeadName = "medicine")
    public JAXBElement<Certificated> createCertificated(Certificated value) {
        return new JAXBElement<Certificated>(_Certificated_QNAME, Certificated.class, null, value);
    }

}
