//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.21 at 05:06:59 PM MSK 
//


package com.epam.xml.medicine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Certificated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Certificated">
 *   &lt;complexContent>
 *     &lt;extension base="{medicine}Medicine">
 *       &lt;sequence>
 *         &lt;element name="certificate" type="{medicine}Certificate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Certificated", propOrder = {
    "certificate"
})
public class Certificated
    extends Medicine
{

    @XmlElement(required = true)
    protected Certificate certificate;

    public Certificated() {
    	super();
    	certificate = new Certificate();
    }
    
    public Certificated(String name, String pharm, String group, String valid, 
    		String analogs, float price, String wrapped, String form, Dosage dosage, Certificate certificate) {
    	super(name, pharm, group, valid, analogs, price, wrapped, form, dosage);
    	this.certificate = certificate;
    }
    
    public Certificated(String name, String pharm, String group, 
    		String analogs, float price, String wrapped, String form, Dosage dosage, Certificate certificate) {
    	super(name, pharm, group, analogs, price, wrapped, form, dosage);
    	this.certificate = certificate;
    }
    
    /**
     * Gets the value of the certificate property.
     * 
     * @return
     *     possible object is
     *     {@link Certificate }
     *     
     */
    public Certificate getCertificate() {
        return certificate;
    }

    /**
     * Sets the value of the certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Certificate }
     *     
     */
    public void setCertificate(Certificate value) {
        this.certificate = value;
    }

	@Override
	public String toString() {
		return "\nCertificated:\n " + super.toString() + "\n certificate=" + certificate + "\n";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((certificate == null) ? 0 : certificate.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		Certificated other = (Certificated) obj;
		if (certificate == null) {
			if (other.certificate != null)
				return false;
		} else if (!certificate.equals(other.certificate))
			return false;
		return true;
	}

}
