//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.21 at 05:06:59 PM MSK 
//


package com.epam.xml.medicine;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Medicine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Medicine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="analogs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="wrapped" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="form">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="pills"/>
 *               &lt;enumeration value="syrup"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dosage" type="{medicine}Dosage"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pharm" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="chemicals"/>
 *             &lt;enumeration value="antibiotics"/>
 *             &lt;enumeration value="vitamins"/>
 *             &lt;enumeration value="vaccine"/>
 *             &lt;enumeration value="homeopatic"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}integer" default="12" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Medicine", propOrder = {
    "analogs",
    "price",
    "wrapped",
    "form",
    "dosage"
})
@XmlSeeAlso({
    Certificated.class
})
public abstract class Medicine {

    @XmlElement(required = true)
    protected String analogs;
    protected float price;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar wrapped;
    @XmlElement(required = true)
    protected String form;
    @XmlElement(required = true)
    protected Dosage dosage;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "pharm", required = true)
    protected String pharm;
    @XmlAttribute(name = "group", required = true)
    protected String group;
    @XmlAttribute(name = "valid")
    protected BigInteger valid;

    public Medicine() {
    	valid = new BigInteger("12");
    	dosage = new Dosage();
    }
    
    public Medicine(String name, String pharm, String group, String valid, 
    		String analogs, float price, String wrapped, String form, Dosage dosage) {
    	this.name = name;
    	this.pharm = pharm;
    	this.group = group;
    	this.valid = new BigInteger(valid);
    	this.analogs = analogs;
    	this.price = price;
    	try {
			this.wrapped = DatatypeFactory.newInstance().newXMLGregorianCalendar(wrapped);
		} catch (DatatypeConfigurationException e) {
		}
    	this.form = form;
    	this.dosage = dosage;
    	
    }
    
    public Medicine(String name, String pharm, String group, 
    		String analogs, float price, String wrapped, String form, Dosage dosage) {
    	this.name = name;
    	this.pharm = pharm;
    	this.group = group;
    	this.valid = new BigInteger("12");
    	this.analogs = analogs;
    	this.price = price;
    	try {
			this.wrapped = DatatypeFactory.newInstance().newXMLGregorianCalendar(wrapped);
		} catch (DatatypeConfigurationException e) {
		}
    	this.form = form;
    	this.dosage = dosage;
    	
    }
    
    /**
     * Gets the value of the analogs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalogs() {
        return analogs;
    }

    /**
     * Sets the value of the analogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalogs(String value) {
        this.analogs = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public float getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(float value) {
        this.price = value;
    }

    /**
     * Gets the value of the wrapped property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWrapped() {
        return wrapped;
    }

    /**
     * Sets the value of the wrapped property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWrapped(XMLGregorianCalendar value) {
        this.wrapped = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Gets the value of the dosage property.
     * 
     * @return
     *     possible object is
     *     {@link Dosage }
     *     
     */
    public Dosage getDosage() {
        return dosage;
    }

    /**
     * Sets the value of the dosage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dosage }
     *     
     */
    public void setDosage(Dosage value) {
        this.dosage = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pharm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharm() {
        return pharm;
    }

    /**
     * Sets the value of the pharm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharm(String value) {
        this.pharm = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValid(BigInteger value) {
        this.valid = value;
    }

	@Override
	public String toString() {
		return "Medicine:\n analogs=" + analogs + "\n price=" + price + "\n wrapped=" + wrapped + "\n form=" + form
				+ "\n dosage=" + dosage + "\n name=" + name + "\n pharm=" + pharm + "\n group=" + group + "\n valid=" + valid
				+ "\n";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((analogs == null) ? 0 : analogs.hashCode());
		result = prime * result + ((dosage == null) ? 0 : dosage.hashCode());
		result = prime * result + ((form == null) ? 0 : form.hashCode());
		result = prime * result + ((group == null) ? 0 : group.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((pharm == null) ? 0 : pharm.hashCode());
		result = prime * result + Float.floatToIntBits(price);
		result = prime * result + ((valid == null) ? 0 : valid.hashCode());
		result = prime * result + ((wrapped == null) ? 0 : wrapped.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Medicine other = (Medicine) obj;
		if (analogs == null) {
			if (other.analogs != null)
				return false;
		} else if (!analogs.equals(other.analogs))
			return false;
		if (dosage == null) {
			if (other.dosage != null)
				return false;
		} else if (!dosage.equals(other.dosage))
			return false;
		if (form == null) {
			if (other.form != null)
				return false;
		} else if (!form.equals(other.form))
			return false;
		if (group == null) {
			if (other.group != null)
				return false;
		} else if (!group.equals(other.group))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (pharm == null) {
			if (other.pharm != null)
				return false;
		} else if (!pharm.equals(other.pharm))
			return false;
		if (Float.floatToIntBits(price) != Float.floatToIntBits(other.price))
			return false;
		if (valid == null) {
			if (other.valid != null)
				return false;
		} else if (!valid.equals(other.valid))
			return false;
		if (wrapped == null) {
			if (other.wrapped != null)
				return false;
		} else if (!wrapped.equals(other.wrapped))
			return false;
		return true;
	}

}
